### ISSUE TITLE
please add support for UTF-8

### ISSUE THREAD

**Issue by OmlineEditor** [iptraf-ng/iptraf-ng#20]
if I have UTF-8 set in my settings Putty, then the graphics are **not** beautiful. if you switch to KOI8-R then the graphics are beautiful.

program version: iptraf-ng 1.1.4
Putty: 0.73
OS 1:  Debian 10 and 9
OS 2:  Ubuntu 20.04 LTS

![koi](https://user-images.githubusercontent.com/13348933/82936506-5c8f6180-9f97-11ea-8527-c53f478f67af.png)

![koi8](https://user-images.githubusercontent.com/13348933/82936539-687b2380-9f97-11ea-87ce-a8c03c9c4dc6.png)

**Comment by pecameron** [comment]
@OmlineEditor I am currently using using Fedora-30 with xfce and xfce4-terminal is showing the same picture as KIO8-R is showing you. What system are you running on? I have never used putty. I have been using fedora since before Fedora-12.
Could you tell me a little about the system you are on? I clone and build iptraf-ng. The master is much more current than 1.1.4. I have not had time to create a new release.

**Comment by vsamel** [comment]
This is fixed in the tree by commit 5905f87e3f9d. Just use current GitHub code or wait for next release, where this will be fixed.

**Comment by OmlineEditor** [comment]
>  What system are you running on? I have never used putty.

OS 1: Debian 10 and 9
OS 2: Ubuntu 20.04 LTS
minimum versions without a graphical shell. console only. to work in the console, use Putty. what other information do you need?



>  wait for next release, where this will be fixed.

I'm waiting for the new version

**Comment by nikoudel** [comment]
Still doesn't work in v1.2.1.

There is a workaround though:
![image](https://user-images.githubusercontent.com/1636683/176256171-5441a25e-5a90-4380-999f-afde85b816ed.png)
